spring:
  devtools:
    restart:
      enable: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.71.132.236:3308/myapi_db
    username: myAPI
    password: P@ssw0rd101.

logging:
  level:
    com.cbj.mapper.*: debug
